### ISSUE TITLE
Publish to PyPI?

### ISSUE THREAD

**Issue by vokal-isaac** [vokal/s3same#4]
Should we publish this to PyPI?  It's already a public repo and MIT-licensed.  Publishing it would make for a shorter install command.

**Comment by brockboland** [comment]
I can't think of any reason not to. Any other potential benefits or drawbacks you can think of? I'm assuming it won't require much effort to do so, right?

**Comment by vokal-isaac** [comment]
I don't really know.  I've never published a package to PyPI before.  Maybe someone on @vokal/systems has thoughts?  (Except that I can't `@`-mention the systems team for some reason.)

**Comment by foresmac** [comment]
@projectweekend publishes [pg-table-markdown](https://github.com/vokal/pg-table-markdown) to PyPI. Take a look there for some of the required setup. I think he also has an account we can use to publish stuff under Vokal; I'll see if I have access to that.

**Comment by foresmac** [comment]
Effectively, you'll need a `setup.py` file (e.g. https://github.com/vokal/pg-table-markdown/blob/master/setup.py, and then you call a command with our PyPI credentials.

**Comment by vokal-isaac** [comment]
I think I've got [`setup.py`](https://github.com/vokal/s3same/blob/master/setup.py) covered—at least, to the point where `s3same` can be `pip`-installed with a git URL.

**Comment by foresmac** [comment]
ok, I'll look for the creds...

**Comment by vokal-isaac** [comment]
Done: https://pypi.python.org/pypi/s3same

**Comment by foresmac** [comment]
I'd tag the commit in github as v0.1 or whatever and make a release for it.

**Comment by foresmac** [comment]
Not strictly necessary, but nice to do.

**Comment by vokal-isaac** [comment]
Good call.  I'd meant to do that and forgot about it.  https://github.com/vokal/s3same/releases/tag/0.1
